### ISSUE TITLE
Suggestion for props

### ISSUE THREAD

**Issue by dux** [lefetmeofefet/yoffee#5]
I would like `innerHTML` of custom elements to be removed from the DOM on custom node init, and I would like to have it in props

Example:

```
<hello-world foo="bar"><b>HELLO</b></hello-world>

props = { foo: 'bar', innerHTML: '<b>HELLO</b>'}
```

**Comment by lefetmeofefet** [comment]
React did the same thing, and it fit nicely there, but here we have the web standard ```<slot>``` tag which probably does what you need. 
If I did want to pass the content as a prop in addition to the ```<slot>``` capability, it would be in ```props.children``` and it would be a reference to the HTML element and not the raw html text. Would that be useful? what do you need it for?

**Comment by dux** [comment]
Props children would be ok as well. I just like to work with dom components. I define them, usually in Svelte, and then I server render pages and populate custom components directly from the server. 

To me, innerHTML is just another property. I use it for example <html-editor>, and innerHTML is data to be edited (like textarea)

Another example is custom button, or info box <s-info type="success" icon="false"> where data in info box is info box data, I just re-wrap it in another HTML elements to give borders, icons, etc.

I assume this is not probably a standard way, but that is how I use it. I could live with that that I have to wrap it in <slot> and it is first and only children, just because it is standard.

**Comment by lefetmeofefet** [comment]
Actually I looked into it more and figured there's no reason not to use ```children``` property of the element itself, and just insert them into the DOM, so simple :)
Example: [](https://jsfiddle.net/Numbnut/xmu902Lq/15/)
And it works exactly like when using ```slot``` tag: [](https://jsfiddle.net/Numbnut/xmu902Lq/17/)
Pretty cool! thanks for the use case.

**Comment by dux** [comment]
perfect!

So you can close this, fix table thing and you have a pretty good thing :)

**Comment by lefetmeofefet** [comment]
I like my components' styles alongside the html as opposed to a central css file. With ```shadowRoot``` css is encapsulated by default. It's still easy to access generated content - define functions on the element and call them from outside. ```element.doSomething = () => {...doing something}```
